// Generated by CoffeeScript 1.4.0
(function() {

  define(['jquery', 'stellar', 'html2canvas', 'blur', 'autosize'], function($) {
    'use strict';
    console.log("'Allo from CoffeeScript!");
    return $(document).ready(function() {
      var resizeInput;
      $('textarea').autosize();
      resizeInput = function() {
        return $(this).attr("size", $(this).val().length + 1);
      };
      $("input[type=\"text\"], input[type=\"email\"]").keyup(resizeInput).each(resizeInput);
      $("a[href^=\"#\"], .nav > li > a, .section-up a, .section-down a").click(function(e) {
        var anchor, offset;
        anchor = $(this);
        if (anchor.attr("href") === '#') {
          offset = 0;
        } else if (document.documentElement.clientWidth <= 480) {
          offset = $(anchor.attr("href")).offset().top;
        } else {
          offset = $(anchor.attr("href")).offset().top;
        }
        $("html, body").stop().animate({
          scrollTop: offset
        }, 1000, "easeInOutQuart");
        return e.preventDefault();
      });
      $.stellar();
      if ($(window).scrollTop() > 450) {
        $(".navbar").addClass('open');
      }
      $(window).on("scroll", function() {
        var scrolltop;
        scrolltop = $(this).scrollTop();
        if (scrolltop > 450) {
          return $(".navbar").addClass('open');
        } else {
          if (scrolltop < 450) {
            return $(".navbar").removeClass('open');
          }
        }
      });
      $('div[id$="-collection"] a[href$="-collection"]').click(function(e) {
        e.preventDefault();
        return $('div[id^="overlay-"]').removeClass('target');
      });
      return $('div[id$="-collection"] a[href^="#overlay-"]').click(function(e) {
        var cap, ext, img, link, name, sectionOverlay, src;
        e.preventDefault();
        $('div[id^="overlay-"]').addClass('target');
        img = $(this).children("img").first();
        src = img.attr("src");
        ext = src.slice(-4);
        name = src.slice(0, -4);
        sectionOverlay = $(this).attr("href");
        $("" + sectionOverlay + " img").prop("src", "" + name + "-lg" + ext);
        console.log("Changed image");
        cap = $("" + sectionOverlay + " .caption").first();
        cap.html($(this).children(".caption").first().html());
        link = img.attr("data-link");
        if (link) {
          return cap.children("p").first().append(" <a href=\"" + link + "\">Visit site ›</a>");
        }
      });
    });
  });

}).call(this);
